export const journalTw = {
  screen: 'flex-1 bg-void',
  safe: 'flex-1',
  list: 'flex-1',
  scrollContent: 'px-base pt-sm pb-base',
  listHeader: 'gap-base mb-sm',
  entrySeparator: 'h-sm',
  listFooter: 'h-[100px]',
  header: 'flex-row items-center justify-between py-sm',
  pageTitle: 'text-h1 font-bold text-ink-primary',
  pageSubtitle: 'text-body text-ink-secondary mt-0.5',
  newBtn:
    'h-10 px-[18px] rounded-[20px] overflow-hidden items-center justify-center border border-white/20',
  newBtnText: 'text-body text-white font-semibold',
  promptCard: 'overflow-hidden w-full self-stretch',
  promptRow: 'flex-row gap-sm items-start w-full',
  promptEmoji: 'text-[22px] mt-0.5',
  promptText: 'text-body text-ink-primary flex-1 italic opacity-90',
  entryCard: 'overflow-hidden w-full self-stretch',
  entryHeader: 'flex-row items-center justify-between mb-1.5',
  entryTitle: 'text-h3 text-ink-primary flex-1',
  entryDate: 'text-caption text-accent-secondary',
  entryPreview: 'text-body text-ink-secondary leading-[22px]',
  entryFooter: 'flex-row justify-between mt-2',
  entryTime: 'text-caption text-ink-tertiary',
  entryWords: 'text-caption text-ink-tertiary',
  emptyCard: 'overflow-hidden w-full self-stretch',
  emptyCardContent: 'items-center gap-base py-3xl',
  emptyEmoji: 'text-[56px]',
  emptyTitle: 'text-h3 text-ink-primary',
  emptySubtitle: 'text-body text-ink-secondary text-center',
  emptyCta: 'w-full self-stretch',
  modalOverlay: 'absolute inset-0 z-[100] justify-end',
  modalBackdrop: 'absolute inset-0 bg-black/50',
  modalKeyboard: 'justify-end',
  modalSheet:
    'rounded-t-[24px] max-h-[92%] overflow-hidden border border-glass-border border-b-0',
  modalScroll: 'p-xl gap-base',
  modalBorderOverlay:
    'absolute inset-0 rounded-t-[24px] border border-white/10 border-b-0',
  modalHandle:
    'w-9 h-1 rounded-sm bg-glass-border self-center mb-sm',
  modalTitle: 'text-h2 text-ink-primary',
  titleInput:
    'text-h3 text-ink-primary border-b border-glass-border py-sm',
  bodyInput: 'text-body-lg text-ink-primary min-h-[140px] max-h-[240px] py-sm',
  modalActions: 'flex-row gap-base mt-sm',
  modalActionBtn: 'flex-1',
  saveHint: 'text-caption text-ink-secondary text-center',
  detailOverlay: 'absolute inset-0 z-[200]',
  detailSafe: 'flex-1',
  detailHeader:
    'flex-row items-center justify-between px-xl py-base border-b border-white/10',
  detailCloseText: 'text-body text-accent-secondary',
  detailMeta: 'text-caption text-ink-tertiary',
  detailScroll: 'flex-1 px-xl',
  detailTitle: 'text-h1 text-ink-primary mt-xl mb-lg',
  detailBody: 'text-body-lg text-ink-secondary leading-[30px]',
} as const;
