export const profileTw = {
  screen: 'flex-1 bg-void',
  safe: 'flex-1',
  scroll: 'flex-1',
  scrollContent: 'px-base pt-sm gap-base',
  scrollFooter: 'h-[100px]',
  heroCard: 'p-xl items-center gap-sm overflow-hidden',
  avatarWrapper: 'relative',
  avatarGradient: 'w-full h-full items-center justify-center',
  avatarEmoji: 'text-[44px]',
  editBadge:
    'absolute bottom-0 right-0 w-[26px] h-[26px] rounded-full bg-accent-primary items-center justify-center border-2 border-void',
  editBadgeText: 'text-xs',
  nameRow: 'items-center gap-0.5',
  profileName: 'text-h1 font-bold text-ink-primary',
  editHint: 'text-caption text-ink-tertiary',
  nameEditRow: 'flex-row items-center gap-sm',
  nameInput:
    'text-h2 text-ink-primary border-b border-accent-secondary min-w-[140px] text-center',
  nameSaveBtn: 'bg-accent-primary px-3.5 py-1.5 rounded-full',
  nameSaveBtnText: 'text-body-sm text-white font-semibold',
  joinedText: 'text-caption text-ink-tertiary',
  avatarPickerCard: 'p-base gap-base',
  pickerTitle: 'text-h3 text-ink-primary',
  pickerGrid: 'flex-row flex-wrap gap-sm',
  pickerItem:
    'w-12 h-12 rounded-full items-center justify-center bg-white/[0.06] border border-white/10',
  pickerItemSelected: 'border-accent-secondary bg-[rgba(124,95,244,0.2)]',
  pickerEmoji: 'text-[26px]',
  sectionTitle: 'text-h3 text-ink-primary px-0.5',
  statsGrid: 'flex-row flex-wrap gap-sm',
  statEmoji: 'text-2xl',
  statValue: 'text-h1 font-bold text-ink-primary',
  statLabel: 'text-caption text-ink-secondary text-center',
  settingsCard: 'overflow-hidden',
  settingRow: 'flex-row items-center p-base gap-base',
  settingIcon:
    'w-9 h-9 rounded-[10px] bg-[rgba(124,95,244,0.15)] items-center justify-center',
  settingIconHighlight: 'bg-[rgba(124,95,244,0.35)]',
  settingIconText: 'text-lg',
  settingTextGroup: 'flex-1',
  settingLabel: 'text-body text-ink-primary font-medium',
  settingSublabel: 'text-caption text-ink-secondary',
  chevron: 'text-h2 text-ink-tertiary',
  divider: 'h-px bg-white/10 ml-16',
  timePickerWrapper: 'px-base pb-sm',
  testNotifBtn: 'mx-base mb-base py-2 items-center',
  testNotifText: 'text-body-sm text-accent-secondary',
  dangerBtn: 'mt-sm',
  timeContainer: 'rounded-lg overflow-hidden p-base gap-base border border-glass-border',
  timeBorder: 'absolute inset-0 rounded-lg border border-white/10',
  timeHeading: 'text-label text-ink-secondary',
  timePickerRow: 'flex-row items-center justify-center gap-sm',
  timeColumn: 'items-center gap-1.5',
  timeArrow: 'w-10 h-8 items-center justify-center rounded-md bg-[rgba(124,95,244,0.15)]',
  timeArrowText: 'text-accent-secondary text-[13px] font-semibold',
  timeValueBox:
    'w-16 h-14 rounded-md items-center justify-center bg-[rgba(124,95,244,0.2)] border border-glass-border',
  timeValueText: 'text-h1 font-bold text-ink-primary',
  timeColon: 'text-h1 text-ink-tertiary mt-1',
  timePeriodColumn: 'gap-2 ml-2',
  timePeriodBtn:
    'px-3.5 py-2 rounded-full bg-white/[0.06] border border-white/10',
  timePeriodBtnActive: 'bg-[rgba(124,95,244,0.3)] border-accent-secondary',
  timePeriodText: 'text-body-sm text-ink-tertiary font-semibold',
  timePeriodTextActive: 'text-accent-secondary',
  timeHint: 'text-caption text-ink-tertiary text-center',
  bannerCard: 'p-base gap-sm overflow-hidden',
  bannerIcon: 'text-[28px]',
  bannerText: 'flex-1 gap-0.5',
  bannerTitle: 'text-h3 text-ink-primary',
  bannerBody: 'text-caption text-ink-secondary',
  bannerBtn: 'px-3.5 py-1.5 rounded-full bg-accent-primary self-start',
  bannerBtnText: 'text-body-sm text-white font-semibold',
} as const;
