export const breatheTw = {
  screen: 'flex-1 bg-void',
  safe: 'flex-1',
  selectionLayout: 'flex-1',
  selectionPinned: 'px-base pt-sm gap-sm pb-xs',
  scroll: 'flex-1',
  scrollContent: 'px-base pt-xs gap-base',
  header: 'flex-row items-center justify-between gap-sm',
  headerText: 'flex-1',
  pageTitle: 'text-h1 font-bold text-ink-primary',
  pageSubtitle: 'text-body text-ink-secondary mt-0.5',
  startHeaderBtn:
    'h-10 px-5 rounded-[20px] overflow-hidden items-center justify-center border border-white/20',
  startHeaderBtnText: 'text-body text-white font-semibold',
  listSectionLabel: 'text-label text-ink-secondary',
  patternSeparator: 'h-sm',
  patternCard: 'overflow-hidden w-full',
  patternCardSelected: 'border-accent-secondary',
  patternCardContent: 'gap-sm',
  patternRow: 'flex-row items-center gap-base',
  patternEmoji: 'text-[28px]',
  patternText: 'flex-1',
  patternName: 'text-h3 text-ink-primary',
  patternMeta:
    'text-body-sm text-ink-primary mt-1 font-semibold [text-shadow-color:rgba(0,0,0,0.4)] [text-shadow-offset:0px_1px] [text-shadow-radius:3px]',
  selectedDot: 'w-2.5 h-2.5 rounded-full bg-accent-secondary',
  patternDesc:
    'text-body-sm text-ink-primary w-full opacity-90 [text-shadow-color:rgba(0,0,0,0.35)] [text-shadow-offset:0px_1px] [text-shadow-radius:2px]',
  detailCard: 'overflow-hidden w-full self-stretch',
  detailCardInner: 'w-full relative overflow-hidden rounded-md py-lg px-base',
  detailGrid: 'flex-row justify-between w-full',
  detailItem: 'items-center gap-1',
  detailValue: 'text-h2 text-ink-primary',
  detailLabel: 'text-label-sm text-ink-tertiary',
  doneCard: 'p-xl items-center gap-sm overflow-hidden',
  doneEmoji: 'text-[48px]',
  doneTitle: 'text-h2 text-ink-primary',
  doneSub: 'text-body text-ink-secondary',
  sessionView: 'flex-1 items-center justify-between py-2xl',
  sessionHeader: 'items-center gap-1',
  sessionTitle: 'text-h2 text-ink-primary',
  sessionCycles: 'text-body text-ink-secondary',
  orbWrapper: 'items-center justify-center flex-1',
  guidance: 'px-3xl',
  guidanceText: 'text-body-lg text-ink-secondary text-center italic',
} as const;
