export const moodTw = {
  screen: 'flex-1 bg-void',
  safe: 'flex-1',
  list: 'flex-1',
  scrollContent: 'px-base pt-sm pb-base',
  listHeader: 'gap-base',
  logSeparator: 'h-sm',
  listFooter: 'h-[100px]',
  pageHeader: 'py-sm',
  pageTitle: 'text-h1 font-bold text-ink-primary',
  pageSubtitle: 'text-body text-ink-secondary mt-0.5',
  chartCard: 'p-base',
  chartContainer: 'gap-base',
  chartTitle: 'text-label text-ink-secondary',
  chartRow: 'flex-row items-end gap-1.5 pb-1',
  barWrapper: 'items-center gap-1',
  barTrack: 'w-full bg-white/[0.06] rounded-md justify-end overflow-hidden',
  barFill: 'w-full rounded-md overflow-hidden relative',
  barShimmer: 'absolute top-0 left-0 right-0 h-1 bg-white/40 rounded-sm',
  dayLabel: 'text-caption text-ink-tertiary',
  dayLabelToday: 'text-accent-secondary',
  barEmoji: 'text-sm text-center',
  summaryCard: 'p-base gap-base',
  sectionLabel: 'text-label text-ink-secondary',
  pillsRow: 'flex-row flex-wrap gap-sm',
  pill: 'flex-row items-center gap-1 px-3 py-1.5 rounded-full border',
  pillEmoji: 'text-base',
  pillLabel: 'text-body-sm font-semibold',
  insightText: 'text-body text-ink-secondary',
  sectionHeader: 'flex-row items-center justify-between',
  sectionTitle: 'text-h3 text-ink-primary',
  entryCard: 'overflow-hidden w-full self-stretch',
  entryRow: 'flex-row items-center gap-base w-full',
  moodBadge: 'w-12 h-12 rounded-full items-center justify-center',
  moodBadgeEmoji: 'text-[26px]',
  entryText: 'flex-1',
  moodLabel: 'text-h3 text-ink-primary',
  moodNote: 'text-caption text-ink-secondary',
  entryMeta: 'items-end',
  entryDate: 'text-body-sm text-ink-secondary',
  entryTime: 'text-caption text-ink-tertiary',
  emptyCard: 'p-2xl items-center gap-base',
  emptyEmoji: 'text-[48px]',
  emptyTitle: 'text-h3 text-ink-primary',
  emptySubtitle: 'text-body text-ink-secondary text-center',
} as const;
